---
- name: Install Homebrew Cask Applications
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: yes  # Accept if app is already installed
  loop: "{{ brew_casks }}"
  become: false
  ignore_errors: yes

- name: Install Homebrew Core Packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_core }}"
  become: false
  ignore_errors: yes

- name: Check if Mac App Store CLI (mas) is installed
  command: which mas
  register: mas_check
  changed_when: false

- name: Install Mac App Store Applications
  command: mas install {{ item.id }}
  loop: "{{ mas_applications }}"
  register: mas_install_result