---
- name: Install non-virtualization Homebrew Cask apps
  tags: [apps]
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: yes
  # everything except virtualization-related casks
  loop: "{{ brew_casks | difference(['virtualbox','multipass','docker']) }}"
  become: false
  ignore_errors: yes

- name: Install virtualization Homebrew Cask apps (skippable inside VM)
  tags: [virtualization, virtualbox, multipass, docker]
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
    accept_external_apps: yes
  # only the virtualization casks that are present in brew_casks
  loop: "{{ ['virtualbox','multipass','docker'] | intersect(brew_casks) }}"
  become: false
  ignore_errors: yes

- name: Install Homebrew Core Packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_core }}"
  become: false
  ignore_errors: yes

- name: Check if Mac App Store CLI (mas) is installed
  command: which mas
  register: mas_check
  changed_when: false

- name: Install Mac App Store Applications
  command: mas install {{ item.id }}
  loop: "{{ mas_applications }}"
  register: mas_install_result