---
- name: Install Dev Tools (non-Docker)
  tags: [devtools]
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ brew_formulae | difference(['docker']) }}"
  become: false
  ignore_errors: yes

- name: Install Docker (skippable inside VM)
  tags: [virtualization, docker]
  community.general.homebrew:
    name: docker
    state: present
  become: false
  ignore_errors: yes

- name: Configure Git global settings
  shell: |
    git config --global user.name "{{ git_global_user_name }}"
    git config --global user.email "{{ git_global_user_email }}"
  become: false

- name: Install pipx for dotrun installation
  tags: [devtools, dotrun]
  community.general.homebrew:
    name: pipx
    state: present
  become: false
  ignore_errors: yes

- name: Ensure pipx is in PATH
  tags: [devtools, dotrun]
  shell: pipx ensurepath
  become: false
  ignore_errors: yes

- name: Install dotrun using pipx
  tags: [devtools, dotrun]
  shell: pipx install dotrun
  become: false
  ignore_errors: yes
