---
galaxy_info:
  author: Gajesh Bhat
  description: Chezmoi-based dotfiles installation and updates
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions: [noble]
    - name: macOS
      versions: [all]
dependencies: []
