---
- name: Create installer cache directory
  ansible.builtin.file:
    path: "{{ installer_cache }}"
    state: directory
    mode: "0755"

- name: System toolchains
  ansible.builtin.import_tasks: debian.yml

- name: User toolchains
  ansible.builtin.import_tasks: common.yml
