---
- name: Create installer cache directory
  ansible.builtin.file:
    path: "{{ installer_cache }}"
    state: directory
    mode: "0755"

- name: Ubuntu language toolchains
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: MacOS language toolchains
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_facts['os_family'] == 'Darwin'

- name: Cross-platform language toolchains
  ansible.builtin.import_tasks: common.yml
