---
galaxy_info:
  author: Gajesh Bhat
  description: Docker Engine service and group
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions: [noble]
dependencies: []
