---
virtualization_qemu_package: "{{ 'qemu-system-arm' if dpkg_arch == 'arm64' else 'qemu-system-x86' }}"
virtualization_groups: "{{ ['libvirt', 'kvm', 'lxd'] + (['vboxusers'] if dpkg_arch == 'amd64' else []) }}"
virtualization_extpack_path: "{{ installer_cache }}/Oracle_VirtualBox_Extension_Pack.vbox-extpack"
