---
- name: Ubuntu 24.04 LTS Workstation Setup
  hosts: localhost
  become: yes
  vars:
    username: ubuntu
    git_global_user_name: "Ubuntu Test"
    git_global_user_email: "UbuntuTest@localhost"
  tasks:
    - import_tasks: playbooks/linux/initial-setup.yml
    - import_tasks: playbooks/linux/install-docker.yml
    - import_tasks: playbooks/linux/install-kvm.yml
    - import_tasks: playbooks/linux/install-lxd.yml
    - import_tasks: playbooks/linux/install-virtualbox.yml
    - import_tasks: playbooks/linux/install-gui-apps.yml
    - import_tasks: playbooks/linux/install-wine.yml
    - import_tasks: playbooks/linux/install-dev-tools.yml
    - import_tasks: playbooks/linux/cleanup.yml
